Add metric functions tests
Sage-Bionetworks/challengescoring pull request #20
Opened 2020-05-15 20:13 UTC by andrewelamb

2020-05-15 20:19 UTC, andrewelamb commented
@thomasyu888 @allaway

This is not ready to merge, but please comment

2020-05-19 19:53 UTC, thomasyu888 requested changes

2020-05-19 19:53 UTC, thomasyu888 commented on R/scoring_functions.R
> +auc <- function(gold, pred){
Duplicated, we have `score_auc`

2020-05-19 19:53 UTC, thomasyu888 commented
Can also merge `develop` back in because this branch has all the validation functions

2020-05-21 04:40 UTC, thomasyu888 commented
I merged my CI in, so the tests will auto run now for you when pushing to the branch.

2020-05-21 15:19 UTC, andrewelamb commented
It looks like check is failing. That's annoying bucause it could be the tests, but it could be any of the other checks that are specific to getting it accepted to CRAN.

2020-05-21 15:22 UTC, andrewelamb commented
package e1071 is required
Backtrace:
 1. testthat::expect_equal(...)
 4. challengescoring::score_mcc(...)
##[error]Error: R CMD check found ERRORs
Execution halted
 7. caret:::confusionMatrix.default(data = pred, reference = gold)
 8. getFromNamespace("confusionMatrix.table", "caret")(...)
 9. caret:::requireNamespaceQuietStop("e1071")

══ testthat results  ═══════════════════════════════════════════════════════════
[ OK: 40 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 1 ]
1. Error: score_mcc (@test-scoring_functions.R#35)

2020-05-21 15:24 UTC, andrewelamb commented
e1071 is a dependency of caret, I wonder why it's not being installed in the test env.

2020-05-21 15:42 UTC, andrewelamb commented
I added e1701 to the description file and that seems to have fixed the error. I also removed the duplicate auc function.

2020-05-21 16:18 UTC, thomasyu888 commented
The test command itself runs really quickly, and I've set it to ignore most things except when it errors out on the tests.  

It may be annoying but it seems like it was useful

2022-09-09 15:33 UTC, closed without merging